export const RecipesTypes: { name: string, value: string }[] = [
    { name: 'carrot', value: 'carrot' },
    { name: 'broccoli', value: 'broccoli' },
    { name: 'asparagus', value: 'asparagus' },
    { name: 'cauliflower', value: 'cauliflower' },
    { name: 'corn', value: 'corn' },
    { name: 'cucumber', value: 'cucumber' },
    { name: 'green pepper', value: 'green pepper' },
    { name: 'lettuce', value: 'lettuce' },
    { name: 'mushrooms', value: 'mushrooms' },
    { name: 'onion', value: 'onion' },
    { name: 'potato', value: 'potato' },
    { name: 'pumpkin', value: 'pumpkin' },
    { name: 'red pepper', value: 'red pepper' },
    { name: 'tomato', value: 'tomato' },
    { name: 'beetroot', value: 'beetroot' },
    { name: 'brussel sprouts', value: 'brussel sprouts' },
    { name: 'peas', value: 'peas' },
    { name: 'zucchini', value: 'zucchini' },
    { name: 'radish', value: 'radish' },
    { name: 'sweet potato', value: 'sweet potato' },
    { name: 'artichoke', value: 'artichoke' },
    { name: 'leek', value: 'leek' },
    { name: 'cabbage', value: 'cabbage' },
    { name: 'celery', value: 'celery' },
    { name: 'chili', value: 'chili' },
    { name: 'garlic', value: 'garlic' },
    { name: 'basil', value: 'basil' },
    { name: 'coriander', value: 'coriander' },
    { name: 'parsley', value: 'parsley' },
    { name: 'dill', value: 'dill' },
    { name: 'rosemary', value: 'rosemary' },
    { name: 'oregano', value: 'oregano' },
    { name: 'cinnamon', value: 'cinnamon' },
    { name: 'saffron', value: 'saffron' },
    { name: 'green bean', value: 'green bean' },
    { name: 'bean', value: 'bean' },
    { name: 'chickpea', value: 'chickpea' },
    { name: 'lentil', value: 'lentil' },
    { name: 'apple', value: 'apple' },
    { name: 'apricot', value: 'apricot' },
    { name: 'avocado', value: 'avocado' },
    { name: 'banana', value: 'banana' },
    { name: 'blackberry', value: 'blackberry' },
    { name: 'blackcurrant', value: 'blackcurrant' },
    { name: 'blueberry', value: 'blueberry' },
    { name: 'boysenberry', value: 'boysenberry' },
    { name: 'cherry', value: 'cherry' },
    { name: 'coconut', value: 'coconut' },
    { name: 'fig', value: 'fig' },
    { name: 'grape', value: 'grape' },
    { name: 'grapefruit', value: 'grapefruit' },
    { name: 'kiwifruit', value: 'kiwifruit' },
    { name: 'lemon', value: 'lemon' },
    { name: 'lime', value: 'lime' },
    { name: 'lychee', value: 'lychee' },
    { name: 'mandarin', value: 'mandarin' },
    { name: 'mango', value: 'mango' },
    { name: 'melon', value: 'melon' },
    { name: 'nectarine', value: 'nectarine' },
    { name: 'orange', value: 'orange' },
    { name: 'papaya', value: 'papaya' },
    { name: 'passion fruit', value: 'passion fruit' },
    { name: 'peach', value: 'peach' },
    { name: 'pear', value: 'pear' },
    { name: 'pineapple', value: 'pineapple' },
    { name: 'plum', value: 'plum' },
    { name: 'pomegranate', value: 'pomegranate' },
    { name: 'quince', value: 'quince' },
    { name: 'raspberry', value: 'raspberry' },
    { name: 'strawberry', value: 'strawberry' },
    { name: 'watermelon', value: 'watermelon' },
    { name: 'salad', value: 'salad' },
    { name: 'pizza', value: 'pizza' },
    { name: 'pasta', value: 'pasta' },
    { name: 'popcorn', value: 'popcorn' },
    { name: 'lobster', value: 'lobster' },
    { name: 'steak', value: 'steak' },
    { name: 'bbq', value: 'bbq' },
    { name: 'pudding', value: 'pudding' },
    { name: 'hamburger', value: 'hamburger' },
    { name: 'pie', value: 'pie' },
    { name: 'cake', value: 'cake' },
    { name: 'sausage', value: 'sausage' },
    { name: 'tacos', value: 'tacos' },
    { name: 'kebab', value: 'kebab' },
    { name: 'poutine', value: 'poutine' },
    { name: 'seafood', value: 'seafood' },
    { name: 'chips', value: 'chips' },
    { name: 'fries', value: 'fries' },
    { name: 'masala', value: 'masala' },
    { name: 'paella', value: 'paella' },
    { name: 'som tam', value: 'som tam' },
    { name: 'chicken', value: 'chicken' },
    { name: 'toast', value: 'toast' },
    { name: 'marzipan', value: 'marzipan' },
    { name: 'tofu', value: 'tofu' },
    { name: 'ketchup', value: 'ketchup' },
    { name: 'hummus', value: 'hummus' },
    { name: 'chili', value: 'chili' },
    { name: 'maple syrup', value: 'maple syrup' },
    { name: 'parma ham', value: 'parma ham' },
    { name: 'fajitas', value: 'fajitas' },
    { name: 'champ', value: 'champ' },
    { name: 'lasagna', value: 'lasagna' },
    { name: 'poke', value: 'poke' },
    { name: 'chocolate', value: 'chocolate' },
    { name: 'croissant', value: 'croissant' },
    { name: 'arepas', value: 'arepas' },
    { name: 'bunny chow', value: 'bunny chow' },
    { name: 'pierogi', value: 'pierogi' },
    { name: 'donuts', value: 'donuts' },
    { name: 'rendang', value: 'rendang' },
    { name: 'sushi', value: 'sushi' },
    { name: 'ice cream', value: 'ice cream' },
    { name: 'duck', value: 'duck' },
    { name: 'curry', value: 'curry' },
    { name: 'beef', value: 'beef' },
    { name: 'goat', value: 'goat' },
    { name: 'lamb', value: 'lamb' },
    { name: 'turkey', value: 'turkey' },
    { name: 'pork', value: 'pork' },
    { name: 'fish', value: 'fish' },
    { name: 'crab', value: 'crab' },
    { name: 'bacon', value: 'bacon' },
    { name: 'ham', value: 'ham' },
    { name: 'pepperoni', value: 'pepperoni' },
    { name: 'salami', value: 'salami' },
    { name: 'ribs', value: 'ribs' }
  ];
  